backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: assets/images
public_folder: /img
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: "Accueil"
        name: "accueil"
        file: "content/_index.md"
        fields:
          - {label: Titre, name: title, widget: string}
          - {label: Slogan banni√®re, name: hero.tagline, widget: string}
    editor:
      preview: true